apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-gcp-secret
  title: Create a GCP Secret
  description: Creates a new secret in GCP Secret Manager.
  tags:
    - gcp
spec:
  type: template
  parameters:
    - title: Secret Details
      required:
        - name
        - value
        - project
      properties:
        project:
          title: Project
          type: string
          description: Select the project where the secret should be created
          enum:
            - project-1
            - project-2
        name:
          title: Secret Name
          type: string
          description: Name of the secret
          pattern: "^[a-zA-Z_0-9\\-]+$"
        value:
          title: Secret Value
          type: string
          ui:field: Secret
          description: The value to store in the secret
        system:
          title: System
          type: string
          description: Select the system that the secret belongs to.
          ui:field: EntityPicker
          ui:options:
            defaultNamespace: default
            catalogFilter:
              - kind: System

  steps:
    - id: create-secret
      name: Create GCP Secret
      action: datolabs:gcp:secrets-manager:create
      input:
        name: ${{ parameters.name }}
        value: ${{ secrets.value }}
        project: ${{ parameters.project }}
        labels:
          system: ${{ parameters.system | parseEntityRef | pick('name') }}

  output:
    links:
      - title: View the secret in GCP Console
        url: https://console.cloud.google.com/security/secret-manager/secret/${{ parameters.name }}/versions?project=${{ parameters.project }}
